pendulum:
  id: "2035"  # The integer unique identifier used for data storage
  length: 0.5  # The pendulum length [m]
  axis_height: 1.5  # The pendulum axis height [m] (Not used in the simulation. Height center body(torso_2_link) + length)
  added_mass: 0.6  # The pendulum added mass (not including the pendulum mass itself) [kg]
  tip_type: "default"  # The pendulum tip type